# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d140b55483d5ad34c040fb825e9bb69751cad821c6dd5f4ecf2c8d3af87914cc726d68421f21fd25bb0af0843cbbaf151aced195ff1db0db464d245a6b5c27e

test:
  secret_key_base: 93148f31e6a8dd1b4557e5a3590f9bb1e4b97ed91c4f49f1984b37cc02ee69c43340f6b91805bf8718520ac2340e03a62535110338248e7f429a72e4d537fc22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
